### ISSUE TITLE
Error while compiling convert_w2v_bin_to_glove_format.py

### ISSUE THREAD

**Issue by Rabia-Noureen** [JohnGiorgi/NER-model-data-preprocessing#1]
Hi @JohnGiorgi  i am using Windows 10 with python 2.7 installed i tried to run the script for Google News pre-trained word embeddings(.bin file extracted from .gz) available at https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing

but i got the following error

![image](https://user-images.githubusercontent.com/29410483/31193313-304da52e-a95d-11e7-8616-9a8e3139a6b2.png)

I have made the following changes to the path variable:

binary_w2v_file_path = "/Users/Acer/tagger-master/convertvec-master/convertvec-master/GoogleNews-vectors-negative300.bin"

Kindly help me fix the issue.

**Comment by JohnGiorgi** [comment]
Hi @Rabia-Noureen,

Just a heads up, I developed this scripts quickly and just for my own usage, so they are unlikely to work for any use cases not identical to my own.

I removed the UTF-8 encoding requirement in the header, this might fix your issue. Try running the script with Python 3 (I have not tested it on Python 2 and that could easily be the problem).

**Comment by Rabia-Noureen** [comment]
@JohnGiorgi Thanks for your response. Today i tried with Python 3 but got an other error

![image](https://user-images.githubusercontent.com/29410483/31234378-34884c88-aa08-11e7-9120-c5da1e59c1f2.png)

No issues i will try to figure something out thanks for your suggestions.
